const SHEETS={community:'COMMUNITY MASTER',property:'PROPERTY MASTER',owner:'OWNER MASTER - PRIVATE',buyer:'BUYER MASTER - PRIVATE',lead:'LEAD TRACKER - PRIVATE',visit:'SITE VISITS - PRIVATE',deal:'DEALS - PRIVATE'};
const HEADERS={
 community:['Community ID','Community Name','Property Type','Community Type','Developer / Builder','RERA Number','Project Status','Launch Year','Completion Year','Total Land Area','Total Units','Total Villas','Total Flats','Blocks / Towers','Floors / Tower','Open Space Area','Green Area','Clubhouse Area','Locality','Area','Landmark','Google Maps','Nearest Metro','Airport Distance','IT / Business Hub','Amenities','Security','CCTV','Power Backup','Water Supply','EV Charging','STP','RWH','Approvals','Occupancy Certificate','Bank Loan','Legal Verification','Community USP','Top Selling Points','Photos','Video','Brochure','Master Plan','Location Map','Remarks'],
 property:['Property ID','Community ID','Property Type','Community Name','BHK','Bedrooms','Bathrooms','Pooja Room','Balconies','Servant Room','Store Room','Facing','Corner','Plot Area','Built-up Area','Carpet Area','UDS','Floor Number','Block / Tower','Flat / Villa Number','Construction Age','Furnishing','Car Parking','Lift','Generator','Maintenance','Permissions','Occupancy Certificate','Locality','Area','Landmark','Google Maps','Sale Price','Payment Mode','Other Charges','Negotiable','Expected Closing Price','Owner ID','Photos','Video','Brochure','Key Highlights','Property Description','Site Visit','Verification Status','Status','Last Updated','Remarks'],
 owner:['Owner ID','Owner Name','Mobile','WhatsApp','Email','Property ID','Ownership Type','Asking Price','Expected Closing Price','Negotiable','Payment Preference','Best Time to Call','Source of Property','Documents Available','Verification Status','Owner Requirement','Owner Remarks','Last Contact','Next Follow-up','Status'],
 buyer:['Buyer ID','Buyer Name','Mobile','WhatsApp','Email','Budget Min','Budget Max','Preferred Locations','Property Type','BHK','Preferred Area','Purpose','Purchase Timeline','Funding','Must-have Requirements','Preferred Amenities','Lead Source','Lead Status','Priority','Last Contact','Next Follow-up','Buyer Remarks'],
 lead:['Lead ID','Buyer ID','Property ID','Lead Source','Enquiry Date','Assigned To','Lead Status','Priority','First Contact','Contact Result','Next Follow-up','WhatsApp Sent','AI Call Status','Site Visit Status','Buyer Feedback','Next Action','Remarks'],
 visit:['Visit ID','Buyer ID','Property ID','Date','Time','Meeting Point','Owner Confirmed','Buyer Confirmed','Visit Completed','Buyer Feedback','Interested','Negotiation Started','Next Follow-up','Remarks'],
 deal:['Deal ID','Buyer ID','Property ID','Community','Deal Value','Deal Stage','Expected Closing','Actual Closing','Commission %','Expected Commission','Actual Commission','Payment Status','Deal Status','Remarks']
};
function setupSheets(){const ss=SpreadsheetApp.getActive();Object.keys(HEADERS).forEach(k=>{const n=SHEETS[k],sh=ss.getSheetByName(n)||ss.insertSheet(n);if(sh.getLastRow()===0)sh.appendRow(HEADERS[k]);});return ss;}
function doGet(){return json_({ok:true,service:'RJ Properties CRM',version:'v3',status:'ready'});}
function doPost(e){try{const d=JSON.parse((e.postData&&e.postData.contents)||'{}');setupSheets();switch(d.leadType){case'buyer':return saveBuyer_(d);case'seller':return saveSeller_(d);case'property':return saveProperty_(d);case'site_visit':return saveVisit_(d);case'deal':return saveDeal_(d);case'voice_request':return saveVoiceRequest_(d);default:throw new Error('Unknown record type');}}catch(err){return json_({ok:false,error:String(err)});}}
function saveBuyer_(d){const ss=SpreadsheetApp.getActive(),id=d.buyerId||d.id||('BUY-'+Utilities.getUuid().slice(0,8)),leadId=d.leadId||('LEAD-'+Utilities.getUuid().slice(0,8));ss.getSheetByName(SHEETS.buyer).appendRow([id,d.name||'',d.phone||'',d.whatsapp||d.phone||'',d.email||'',d.budgetMin||'',d.budgetMax||d.budget||'',d.location||'',d.propertyType||'',d.bhk||'',d.preferredArea||'',d.purpose||'',d.purchaseTimeline||'',d.funding||'',d.requirements||'',d.amenities||'',d.source||'Website','New',d.priority||'Normal','',d.nextFollowUp||'',d.buyerRemarks||'']);ss.getSheetByName(SHEETS.lead).appendRow([leadId,id,d.propertyId||'',d.source||'Website',new Date(),'','New',d.priority||'Normal','','',d.nextFollowUp||'','No','Not Started','Not Started','','Follow up','']);return json_({ok:true,id,leadId,type:'buyer'});}
function saveSeller_(d){d.leadType='property';return saveProperty_(d);}
function saveProperty_(d){const ss=SpreadsheetApp.getActive(),propertyId=d.propertyId||d.id||('PROP-'+Utilities.getUuid().slice(0,8)),ownerId=d.ownerId||('OWN-'+Utilities.getUuid().slice(0,8));ss.getSheetByName(SHEETS.property).appendRow([propertyId,d.communityId||'',d.propertyType||'',d.communityName||'',d.bhk||'',d.bedrooms||'',d.baths||d.bathrooms||'',d.pooja||'',d.balcony||'',d.servantRoom||'',d.storeroom||'',d.facing||'',d.corner||'',d.plotArea||'',d.builtUpArea||'',d.carpetArea||'',d.uds||'',d.floorNumber||'',d.blockNumber||d.blockTower||'',d.flatVillaNumber||'',d.constructionAge||'',d.furnishingStatus||d.furnishing||'',d.carParking||'',d.lift||'',d.generator||'',d.maintenanceCharges||d.maintenance||'',d.permissions||'',d.occupancyCertificate||'',d.locality||'',d.area||'',d.landmark||'',d.googleMaps||'',d.salePrice||'',d.paymentMode||'',d.otherCharges||'',d.negotiable||'',d.expectedClosingPrice||'',ownerId,d.photosLink||d.photos||'',d.videoLink||d.video||'',d.brochure||'',d.keyHighlights||'',d.propertyDescription||d.details||'',d.siteVisit||'',d.verificationStatus||'Pending',d.status||'New',new Date(),d.remarks||'']);ss.getSheetByName(SHEETS.owner).appendRow([ownerId,d.ownerName||d.name||'',d.ownerContact||d.phone||'',d.ownerWhatsApp||d.phone||'',d.ownerEmail||d.email||'',propertyId,d.ownershipType||'',d.salePrice||'',d.expectedClosingPrice||'',d.negotiable||'',d.paymentMode||'',d.bestTimeToCall||'',d.source||'Website',d.documentsAvailable||'',d.verificationStatus||'Pending',d.ownerRequirement||'',d.ownerNotes||'', '',d.nextFollowUp||'','New']);return json_({ok:true,id:propertyId,ownerId,type:'property'});}
function saveVisit_(d){const id=d.id||('VIS-'+Utilities.getUuid().slice(0,8));SpreadsheetApp.getActive().getSheetByName(SHEETS.visit).appendRow([id,d.buyerId||'',d.propertyId||'',d.date||'',d.time||'',d.meetingPoint||'',d.ownerConfirmed||'',d.buyerConfirmed||'',d.visitCompleted||'',d.buyerFeedback||'',d.interested||'',d.negotiationStarted||'',d.nextFollowUp||'',d.remarks||'']);return json_({ok:true,id,type:'site_visit'});}
function saveDeal_(d){const id=d.id||('DEAL-'+Utilities.getUuid().slice(0,8));SpreadsheetApp.getActive().getSheetByName(SHEETS.deal).appendRow([id,d.buyerId||'',d.propertyId||'',d.community||'',d.dealValue||'',d.dealStage||'Negotiation',d.expectedClosing||'',d.actualClosing||'',d.commissionPercent||'',d.expectedCommission||'',d.actualCommission||'',d.paymentStatus||'',d.dealStatus||'Open',d.remarks||'']);return json_({ok:true,id,type:'deal'});}
function saveVoiceRequest_(d){const sh=SpreadsheetApp.getActive().getSheetByName(SHEETS.lead);sh.appendRow([d.leadId||('LEAD-'+Utilities.getUuid().slice(0,8)),d.buyerId||'',d.propertyId||'','AI Voice',new Date(),'','Contact Pending','High','','',d.nextFollowUp||'','No','Queued','Not Started','','AI call requested',d.notes||'']);return json_({ok:true,type:'voice_request',status:'queued'});}
function json_(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON);}
